/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from "kysely";

export type Generated<T> = T extends ColumnType<infer S, infer I, infer U>
  ? ColumnType<S, I | undefined, U>
  : ColumnType<T, T | undefined, T>;

export interface ConceptArt {
  alt_text: string;
  caption: Generated<string>;
  filename: string;
  id: Generated<number>;
  type: Generated<string>;
}

export interface Credits {
  ep_id: number | null;
  id: Generated<number>;
  role: string;
  superrole: string;
  team_id: number | null;
}

export interface EpisodeCovers {
  alt_text: string;
  filename: string;
  id: Generated<number>;
}

export interface Episodes {
  cover_id: Generated<number>;
  description: string;
  ep_num: number;
  id: Generated<number>;
  link_amazon: Generated<string>;
  link_apple: Generated<string>;
  link_spotify: Generated<string>;
  season_ep_num: number | null;
  season_id: Generated<number>;
  slug: string;
  title: string;
  transcript_filename: string | null;
  triggers: string;
}

export interface NotfoundArt {
  alt_text: string;
  filename: string;
  id: Generated<number>;
}

export interface Seasons {
  cover_alt_text: Generated<string>;
  cover_filename: string;
  id: Generated<number>;
  season_num: number;
}

export interface ShowLinks {
  icon_alt_text: Generated<string>;
  icon_filename: Generated<string>;
  id: Generated<number>;
  link: string;
  name: string;
  type: string;
}

export interface Team {
  bio: Generated<string>;
  fname: string;
  full_name: string;
  headshot_filename: Generated<string>;
  id: Generated<number>;
  lname: string;
  projects: Generated<string>;
  pronouns: Generated<string>;
  quote: Generated<string>;
  socials: Generated<string>;
}

export interface DB {
  concept_art: ConceptArt;
  credits: Credits;
  episode_covers: EpisodeCovers;
  episodes: Episodes;
  notfound_art: NotfoundArt;
  seasons: Seasons;
  show_links: ShowLinks;
  team: Team;
}
